"""
Comprehensive Construction Materials Library
Contains 300+ materials with specifications, brands, grades, and regional pricing
For Indian residential and commercial construction projects
"""

from typing import List, Dict, Any
from datetime import datetime

# Material Categories
CATEGORIES = {
    "STRUCTURAL": "Structural Materials",
    "CEMENT": "Cement & Binding Materials",
    "STEEL": "Steel & Reinforcement",
    "AGGREGATES": "Aggregates & Sand",
    "MASONRY": "Bricks, Blocks & Masonry",
    "FLOORING": "Flooring & Tiles",
    "PAINTING": "Paints & Coatings",
    "PLUMBING": "Plumbing Materials",
    "ELECTRICAL": "Electrical Materials",
    "WATERPROOFING": "Waterproofing & Insulation",
    "DOORS_WINDOWS": "Doors & Windows",
    "HARDWARE": "Hardware & Fittings",
    "WOOD": "Wood & Plywood",
    "FINISHING": "Finishing Materials",
    "ROOFING": "Roofing Materials",
    "GLASS": "Glass & Glazing",
    "KITCHEN": "Kitchen & Sanitary",
    "SAFETY": "Safety & Fire Protection",
}

# Quality Grades
GRADES = ["Economy", "Standard", "Premium", "Luxury"]

# Regional pricing multipliers (base: Bangalore = 1.0)
REGIONAL_MULTIPLIERS = {
    "Bangalore": 1.0,
    "Mumbai": 1.15,
    "Delhi": 1.08,
    "Chennai": 0.95,
    "Hyderabad": 0.92,
    "Pune": 1.05,
    "Kolkata": 0.88,
    "Ahmedabad": 0.90,
    "Kochi": 0.98,
    "Jaipur": 0.85,
}


def get_comprehensive_materials_library() -> List[Dict[str, Any]]:
    """
    Returns comprehensive list of 300+ construction materials
    with specifications, brands, and pricing
    """
    materials = []
    
    # ==================== CEMENT & BINDING MATERIALS ====================
    cement_materials = [
        {
            "item_name": "OPC 53 Grade Cement",
            "category": "CEMENT",
            "description": "Ordinary Portland Cement 53 Grade for structural work",
            "unit": "bag",
            "specifications": "IS 12269, 53 Grade, 50kg bag",
            "rate_min": 350,
            "rate_max": 420,
            "brands": [
                {"name": "UltraTech", "rate": 400, "grade": "Premium"},
                {"name": "ACC", "rate": 390, "grade": "Premium"},
                {"name": "Ambuja", "rate": 385, "grade": "Premium"},
                {"name": "Dalmia", "rate": 370, "grade": "Standard"},
                {"name": "Ramco", "rate": 365, "grade": "Standard"},
                {"name": "Birla", "rate": 380, "grade": "Premium"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 3,
        },
        {
            "item_name": "OPC 43 Grade Cement",
            "category": "CEMENT",
            "description": "Ordinary Portland Cement 43 Grade for general work",
            "unit": "bag",
            "specifications": "IS 8112, 43 Grade, 50kg bag",
            "rate_min": 320,
            "rate_max": 380,
            "brands": [
                {"name": "UltraTech", "rate": 370, "grade": "Premium"},
                {"name": "ACC", "rate": 360, "grade": "Premium"},
                {"name": "Ambuja", "rate": 355, "grade": "Standard"},
                {"name": "Chettinad", "rate": 340, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 3,
        },
        {
            "item_name": "PPC Cement (Pozzolana)",
            "category": "CEMENT",
            "description": "Portland Pozzolana Cement for general construction",
            "unit": "bag",
            "specifications": "IS 1489, PPC, 50kg bag",
            "rate_min": 300,
            "rate_max": 360,
            "brands": [
                {"name": "UltraTech PPC", "rate": 350, "grade": "Premium"},
                {"name": "ACC Gold", "rate": 345, "grade": "Premium"},
                {"name": "Ambuja Plus", "rate": 340, "grade": "Standard"},
                {"name": "Zuari", "rate": 320, "grade": "Economy"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 3,
        },
        {
            "item_name": "White Cement",
            "category": "CEMENT",
            "description": "White Portland Cement for decorative work",
            "unit": "kg",
            "specifications": "IS 8042, White Cement",
            "rate_min": 25,
            "rate_max": 40,
            "brands": [
                {"name": "Birla White", "rate": 35, "grade": "Premium"},
                {"name": "JK White", "rate": 32, "grade": "Standard"},
                {"name": "UltraTech White", "rate": 38, "grade": "Premium"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Ready Mix Concrete M20",
            "category": "CEMENT",
            "description": "Ready Mix Concrete M20 grade",
            "unit": "cum",
            "specifications": "IS 456, M20 Grade, 20 MPa",
            "rate_min": 4500,
            "rate_max": 5500,
            "brands": [
                {"name": "UltraTech RMC", "rate": 5200, "grade": "Premium"},
                {"name": "ACC RMC", "rate": 5000, "grade": "Premium"},
                {"name": "RDC Concrete", "rate": 4800, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 2,
        },
        {
            "item_name": "Ready Mix Concrete M25",
            "category": "CEMENT",
            "description": "Ready Mix Concrete M25 grade for columns/beams",
            "unit": "cum",
            "specifications": "IS 456, M25 Grade, 25 MPa",
            "rate_min": 5000,
            "rate_max": 6200,
            "brands": [
                {"name": "UltraTech RMC", "rate": 5800, "grade": "Premium"},
                {"name": "ACC RMC", "rate": 5600, "grade": "Premium"},
                {"name": "Nuvoco", "rate": 5400, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 2,
        },
        {
            "item_name": "Ready Mix Concrete M30",
            "category": "CEMENT",
            "description": "Ready Mix Concrete M30 grade for high-strength work",
            "unit": "cum",
            "specifications": "IS 456, M30 Grade, 30 MPa",
            "rate_min": 5500,
            "rate_max": 6800,
            "brands": [
                {"name": "UltraTech RMC", "rate": 6400, "grade": "Premium"},
                {"name": "ACC RMC", "rate": 6200, "grade": "Premium"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 2,
        },
    ]
    materials.extend(cement_materials)
    
    # ==================== STEEL & REINFORCEMENT ====================
    steel_materials = [
        {
            "item_name": "TMT Steel Bars Fe500D - 8mm",
            "category": "STEEL",
            "description": "TMT reinforcement bars 8mm diameter",
            "unit": "kg",
            "specifications": "IS 1786, Fe500D, 8mm dia",
            "rate_min": 58,
            "rate_max": 72,
            "brands": [
                {"name": "TATA Tiscon", "rate": 70, "grade": "Premium"},
                {"name": "JSW Neosteel", "rate": 68, "grade": "Premium"},
                {"name": "SAIL TMT", "rate": 65, "grade": "Standard"},
                {"name": "Vizag Steel", "rate": 62, "grade": "Standard"},
                {"name": "Kamdhenu", "rate": 60, "grade": "Economy"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "TMT Steel Bars Fe500D - 10mm",
            "category": "STEEL",
            "description": "TMT reinforcement bars 10mm diameter",
            "unit": "kg",
            "specifications": "IS 1786, Fe500D, 10mm dia",
            "rate_min": 56,
            "rate_max": 70,
            "brands": [
                {"name": "TATA Tiscon", "rate": 68, "grade": "Premium"},
                {"name": "JSW Neosteel", "rate": 66, "grade": "Premium"},
                {"name": "SAIL TMT", "rate": 63, "grade": "Standard"},
                {"name": "Jindal Panther", "rate": 64, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "TMT Steel Bars Fe500D - 12mm",
            "category": "STEEL",
            "description": "TMT reinforcement bars 12mm diameter for main bars",
            "unit": "kg",
            "specifications": "IS 1786, Fe500D, 12mm dia",
            "rate_min": 55,
            "rate_max": 68,
            "brands": [
                {"name": "TATA Tiscon", "rate": 66, "grade": "Premium"},
                {"name": "JSW Neosteel", "rate": 64, "grade": "Premium"},
                {"name": "SAIL TMT", "rate": 61, "grade": "Standard"},
                {"name": "Shyam Steel", "rate": 58, "grade": "Economy"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "TMT Steel Bars Fe500D - 16mm",
            "category": "STEEL",
            "description": "TMT reinforcement bars 16mm diameter for columns",
            "unit": "kg",
            "specifications": "IS 1786, Fe500D, 16mm dia",
            "rate_min": 54,
            "rate_max": 66,
            "brands": [
                {"name": "TATA Tiscon", "rate": 64, "grade": "Premium"},
                {"name": "JSW Neosteel", "rate": 62, "grade": "Premium"},
                {"name": "Essar Steel", "rate": 60, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "TMT Steel Bars Fe500D - 20mm",
            "category": "STEEL",
            "description": "TMT reinforcement bars 20mm diameter for heavy columns",
            "unit": "kg",
            "specifications": "IS 1786, Fe500D, 20mm dia",
            "rate_min": 54,
            "rate_max": 65,
            "brands": [
                {"name": "TATA Tiscon", "rate": 63, "grade": "Premium"},
                {"name": "JSW Neosteel", "rate": 61, "grade": "Premium"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "TMT Steel Bars Fe500D - 25mm",
            "category": "STEEL",
            "description": "TMT reinforcement bars 25mm diameter for foundations",
            "unit": "kg",
            "specifications": "IS 1786, Fe500D, 25mm dia",
            "rate_min": 54,
            "rate_max": 64,
            "brands": [
                {"name": "TATA Tiscon", "rate": 62, "grade": "Premium"},
                {"name": "JSW Neosteel", "rate": 60, "grade": "Premium"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Binding Wire",
            "category": "STEEL",
            "description": "Soft annealed binding wire for tying rebars",
            "unit": "kg",
            "specifications": "IS 280, 18 SWG",
            "rate_min": 55,
            "rate_max": 75,
            "brands": [
                {"name": "TATA", "rate": 70, "grade": "Premium"},
                {"name": "JSW", "rate": 68, "grade": "Standard"},
                {"name": "Local", "rate": 58, "grade": "Economy"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "Welded Wire Mesh",
            "category": "STEEL",
            "description": "Welded wire mesh for slab reinforcement",
            "unit": "sqm",
            "specifications": "IS 1566, 6mm dia, 150x150mm",
            "rate_min": 120,
            "rate_max": 180,
            "brands": [
                {"name": "TATA Wiron", "rate": 165, "grade": "Premium"},
                {"name": "Jindal", "rate": 150, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 8,
        },
        {
            "item_name": "Structural Steel - I Beam",
            "category": "STEEL",
            "description": "I-Section steel beam for structural framing",
            "unit": "kg",
            "specifications": "IS 2062, ISMB sections",
            "rate_min": 58,
            "rate_max": 72,
            "brands": [
                {"name": "SAIL", "rate": 68, "grade": "Premium"},
                {"name": "Jindal", "rate": 65, "grade": "Standard"},
                {"name": "JSW", "rate": 70, "grade": "Premium"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 3,
        },
        {
            "item_name": "MS Angle Iron",
            "category": "STEEL",
            "description": "Mild steel angle for miscellaneous work",
            "unit": "kg",
            "specifications": "IS 2062, various sizes",
            "rate_min": 55,
            "rate_max": 68,
            "brands": [
                {"name": "SAIL", "rate": 64, "grade": "Premium"},
                {"name": "Jindal", "rate": 60, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 5,
        },
    ]
    materials.extend(steel_materials)
    
    # ==================== AGGREGATES & SAND ====================
    aggregate_materials = [
        {
            "item_name": "Coarse Aggregate 20mm",
            "category": "AGGREGATES",
            "description": "Crushed stone aggregate 20mm down for concrete",
            "unit": "cum",
            "specifications": "IS 383, 20mm nominal size",
            "rate_min": 1200,
            "rate_max": 1800,
            "brands": [
                {"name": "Machine Crushed", "rate": 1600, "grade": "Premium"},
                {"name": "Quarry Run", "rate": 1400, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Coarse Aggregate 40mm",
            "category": "AGGREGATES",
            "description": "Crushed stone aggregate 40mm for foundations",
            "unit": "cum",
            "specifications": "IS 383, 40mm nominal size",
            "rate_min": 1100,
            "rate_max": 1600,
            "brands": [
                {"name": "Machine Crushed", "rate": 1450, "grade": "Premium"},
                {"name": "Quarry Run", "rate": 1250, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Fine Aggregate 12mm",
            "category": "AGGREGATES",
            "description": "Crushed stone chips 12mm for plastering",
            "unit": "cum",
            "specifications": "IS 383, 12mm down",
            "rate_min": 1400,
            "rate_max": 2000,
            "brands": [
                {"name": "Machine Crushed", "rate": 1800, "grade": "Premium"},
                {"name": "Quarry Dust", "rate": 1500, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "River Sand (Fine)",
            "category": "AGGREGATES",
            "description": "Natural river sand for concrete and plastering",
            "unit": "cum",
            "specifications": "IS 383, Zone II",
            "rate_min": 2500,
            "rate_max": 4500,
            "brands": [
                {"name": "River Sand Zone II", "rate": 3800, "grade": "Premium"},
                {"name": "River Sand Zone III", "rate": 3200, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 8,
        },
        {
            "item_name": "M-Sand (Manufactured Sand)",
            "category": "AGGREGATES",
            "description": "Manufactured sand as river sand alternative",
            "unit": "cum",
            "specifications": "IS 383, Manufactured",
            "rate_min": 1500,
            "rate_max": 2200,
            "brands": [
                {"name": "VSI M-Sand", "rate": 2000, "grade": "Premium"},
                {"name": "Robo Sand", "rate": 1800, "grade": "Standard"},
                {"name": "Crusher Dust", "rate": 1600, "grade": "Economy"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "P-Sand (Plastering Sand)",
            "category": "AGGREGATES",
            "description": "Manufactured plastering sand",
            "unit": "cum",
            "specifications": "Graded fine aggregate for plastering",
            "rate_min": 1800,
            "rate_max": 2500,
            "brands": [
                {"name": "P-Sand Premium", "rate": 2300, "grade": "Premium"},
                {"name": "P-Sand Standard", "rate": 2000, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Brick Bat Aggregate",
            "category": "AGGREGATES",
            "description": "Broken brick pieces for waterproofing terraces",
            "unit": "cum",
            "specifications": "Well burnt brick bats",
            "rate_min": 800,
            "rate_max": 1200,
            "brands": [
                {"name": "Brick Jelly", "rate": 1000, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 10,
        },
    ]
    materials.extend(aggregate_materials)
    
    # ==================== BRICKS, BLOCKS & MASONRY ====================
    masonry_materials = [
        {
            "item_name": "Red Clay Bricks (First Class)",
            "category": "MASONRY",
            "description": "First class burnt clay bricks",
            "unit": "nos",
            "specifications": "IS 1077, 230x115x75mm",
            "rate_min": 7,
            "rate_max": 12,
            "brands": [
                {"name": "Table Moulded", "rate": 10, "grade": "Premium"},
                {"name": "Machine Made", "rate": 9, "grade": "Standard"},
                {"name": "Country Burnt", "rate": 7.5, "grade": "Economy"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Fly Ash Bricks",
            "category": "MASONRY",
            "description": "Eco-friendly fly ash bricks",
            "unit": "nos",
            "specifications": "IS 12894, 230x110x75mm",
            "rate_min": 5,
            "rate_max": 8,
            "brands": [
                {"name": "AAC Grade", "rate": 7.5, "grade": "Premium"},
                {"name": "Standard Grade", "rate": 6, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 3,
        },
        {
            "item_name": "AAC Blocks 4 inch",
            "category": "MASONRY",
            "description": "Autoclaved Aerated Concrete blocks 100mm",
            "unit": "cum",
            "specifications": "IS 2185, 600x200x100mm",
            "rate_min": 3500,
            "rate_max": 4500,
            "brands": [
                {"name": "Ultratech Xtralite", "rate": 4200, "grade": "Premium"},
                {"name": "JK Lakshmi", "rate": 4000, "grade": "Premium"},
                {"name": "Magicrete", "rate": 3800, "grade": "Standard"},
                {"name": "Siporex", "rate": 4100, "grade": "Premium"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 3,
        },
        {
            "item_name": "AAC Blocks 6 inch",
            "category": "MASONRY",
            "description": "Autoclaved Aerated Concrete blocks 150mm",
            "unit": "cum",
            "specifications": "IS 2185, 600x200x150mm",
            "rate_min": 3400,
            "rate_max": 4400,
            "brands": [
                {"name": "Ultratech Xtralite", "rate": 4100, "grade": "Premium"},
                {"name": "JK Lakshmi", "rate": 3900, "grade": "Premium"},
                {"name": "Magicrete", "rate": 3700, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 3,
        },
        {
            "item_name": "AAC Blocks 8 inch",
            "category": "MASONRY",
            "description": "Autoclaved Aerated Concrete blocks 200mm",
            "unit": "cum",
            "specifications": "IS 2185, 600x200x200mm",
            "rate_min": 3300,
            "rate_max": 4300,
            "brands": [
                {"name": "Ultratech Xtralite", "rate": 4000, "grade": "Premium"},
                {"name": "JK Lakshmi", "rate": 3800, "grade": "Premium"},
                {"name": "Renacon", "rate": 3600, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 3,
        },
        {
            "item_name": "Solid Concrete Blocks 6 inch",
            "category": "MASONRY",
            "description": "Solid concrete blocks 150mm thick",
            "unit": "nos",
            "specifications": "IS 2185, 400x200x150mm",
            "rate_min": 35,
            "rate_max": 55,
            "brands": [
                {"name": "Machine Made", "rate": 48, "grade": "Premium"},
                {"name": "Vibro Compacted", "rate": 42, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 3,
        },
        {
            "item_name": "Hollow Concrete Blocks 6 inch",
            "category": "MASONRY",
            "description": "Hollow concrete blocks 150mm thick",
            "unit": "nos",
            "specifications": "IS 2185, 400x200x150mm",
            "rate_min": 30,
            "rate_max": 45,
            "brands": [
                {"name": "Machine Made", "rate": 40, "grade": "Premium"},
                {"name": "Standard", "rate": 35, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 3,
        },
        {
            "item_name": "Hollow Concrete Blocks 8 inch",
            "category": "MASONRY",
            "description": "Hollow concrete blocks 200mm thick",
            "unit": "nos",
            "specifications": "IS 2185, 400x200x200mm",
            "rate_min": 38,
            "rate_max": 55,
            "brands": [
                {"name": "Machine Made", "rate": 50, "grade": "Premium"},
                {"name": "Standard", "rate": 42, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 3,
        },
        {
            "item_name": "Glass Blocks",
            "category": "MASONRY",
            "description": "Decorative glass blocks for partitions",
            "unit": "nos",
            "specifications": "190x190x80mm clear/colored",
            "rate_min": 250,
            "rate_max": 500,
            "brands": [
                {"name": "Saint Gobain", "rate": 450, "grade": "Premium"},
                {"name": "Imported", "rate": 400, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 5,
        },
    ]
    materials.extend(masonry_materials)
    
    # ==================== FLOORING & TILES ====================
    flooring_materials = [
        {
            "item_name": "Vitrified Tiles 600x600mm",
            "category": "FLOORING",
            "description": "Double charged vitrified tiles for flooring",
            "unit": "sqft",
            "specifications": "600x600mm, 8-10mm thick",
            "rate_min": 35,
            "rate_max": 120,
            "brands": [
                {"name": "Kajaria", "rate": 85, "grade": "Premium"},
                {"name": "Somany", "rate": 75, "grade": "Premium"},
                {"name": "Nitco", "rate": 70, "grade": "Standard"},
                {"name": "Orient Bell", "rate": 65, "grade": "Standard"},
                {"name": "RAK Ceramics", "rate": 90, "grade": "Premium"},
                {"name": "Johnson", "rate": 60, "grade": "Standard"},
                {"name": "Simpolo", "rate": 55, "grade": "Economy"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Vitrified Tiles 800x800mm",
            "category": "FLOORING",
            "description": "Large format vitrified tiles for living areas",
            "unit": "sqft",
            "specifications": "800x800mm, 9-11mm thick",
            "rate_min": 50,
            "rate_max": 150,
            "brands": [
                {"name": "Kajaria Eternity", "rate": 120, "grade": "Premium"},
                {"name": "Somany", "rate": 100, "grade": "Premium"},
                {"name": "AGL", "rate": 90, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 8,
        },
        {
            "item_name": "Ceramic Wall Tiles 300x450mm",
            "category": "FLOORING",
            "description": "Ceramic tiles for bathroom/kitchen walls",
            "unit": "sqft",
            "specifications": "300x450mm, 6-8mm thick",
            "rate_min": 25,
            "rate_max": 80,
            "brands": [
                {"name": "Kajaria", "rate": 55, "grade": "Premium"},
                {"name": "Somany", "rate": 50, "grade": "Premium"},
                {"name": "Orient Bell", "rate": 40, "grade": "Standard"},
                {"name": "Asian Granito", "rate": 35, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Anti-Skid Floor Tiles",
            "category": "FLOORING",
            "description": "Anti-skid tiles for bathrooms and balconies",
            "unit": "sqft",
            "specifications": "300x300mm, matt finish",
            "rate_min": 30,
            "rate_max": 75,
            "brands": [
                {"name": "Kajaria", "rate": 60, "grade": "Premium"},
                {"name": "Somany", "rate": 55, "grade": "Premium"},
                {"name": "Johnson", "rate": 45, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Parking Tiles 400x400mm",
            "category": "FLOORING",
            "description": "Heavy duty tiles for parking and driveways",
            "unit": "sqft",
            "specifications": "400x400mm, 12mm thick, anti-skid",
            "rate_min": 35,
            "rate_max": 80,
            "brands": [
                {"name": "Kajaria Outdoor", "rate": 65, "grade": "Premium"},
                {"name": "Orient Heavy Duty", "rate": 55, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Granite Flooring (Polished)",
            "category": "FLOORING",
            "description": "Polished granite slabs for flooring",
            "unit": "sqft",
            "specifications": "18-20mm thick, polished finish",
            "rate_min": 80,
            "rate_max": 300,
            "brands": [
                {"name": "Black Galaxy", "rate": 250, "grade": "Luxury"},
                {"name": "Tan Brown", "rate": 150, "grade": "Premium"},
                {"name": "Steel Grey", "rate": 120, "grade": "Premium"},
                {"name": "Kuppam Green", "rate": 100, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "Italian Marble Flooring",
            "category": "FLOORING",
            "description": "Imported Italian marble for premium flooring",
            "unit": "sqft",
            "specifications": "18-20mm thick, polished",
            "rate_min": 200,
            "rate_max": 800,
            "brands": [
                {"name": "Statuario", "rate": 700, "grade": "Luxury"},
                {"name": "Carrara White", "rate": 500, "grade": "Luxury"},
                {"name": "Botticino", "rate": 350, "grade": "Premium"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 12,
        },
        {
            "item_name": "Indian Marble Flooring",
            "category": "FLOORING",
            "description": "Indian marble for flooring",
            "unit": "sqft",
            "specifications": "18-20mm thick, polished",
            "rate_min": 60,
            "rate_max": 200,
            "brands": [
                {"name": "Makrana White", "rate": 180, "grade": "Premium"},
                {"name": "Dungri Marble", "rate": 100, "grade": "Standard"},
                {"name": "Katni Marble", "rate": 80, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "Kota Stone Flooring",
            "category": "FLOORING",
            "description": "Natural Kota stone for flooring",
            "unit": "sqft",
            "specifications": "20-25mm thick, natural/polished",
            "rate_min": 25,
            "rate_max": 50,
            "brands": [
                {"name": "Kota Blue Polished", "rate": 45, "grade": "Premium"},
                {"name": "Kota Brown Natural", "rate": 35, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 8,
        },
        {
            "item_name": "Wooden Flooring (Laminate)",
            "category": "FLOORING",
            "description": "Laminate wooden flooring",
            "unit": "sqft",
            "specifications": "8mm thick, AC3/AC4 grade",
            "rate_min": 60,
            "rate_max": 180,
            "brands": [
                {"name": "Pergo", "rate": 160, "grade": "Premium"},
                {"name": "Quick Step", "rate": 140, "grade": "Premium"},
                {"name": "Greenply", "rate": 100, "grade": "Standard"},
                {"name": "Action Tesa", "rate": 80, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "Wooden Flooring (Engineered)",
            "category": "FLOORING",
            "description": "Engineered wood flooring",
            "unit": "sqft",
            "specifications": "14mm thick, multi-layer",
            "rate_min": 150,
            "rate_max": 400,
            "brands": [
                {"name": "Pergo Sensation", "rate": 350, "grade": "Luxury"},
                {"name": "Kahrs", "rate": 300, "grade": "Premium"},
                {"name": "Mikasa", "rate": 200, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "Tile Adhesive",
            "category": "FLOORING",
            "description": "Cement-based tile adhesive",
            "unit": "bag",
            "specifications": "20kg bag, grey/white",
            "rate_min": 350,
            "rate_max": 600,
            "brands": [
                {"name": "MYK Laticrete", "rate": 550, "grade": "Premium"},
                {"name": "Roff", "rate": 500, "grade": "Premium"},
                {"name": "Ardex Endura", "rate": 480, "grade": "Standard"},
                {"name": "Weber", "rate": 450, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Tile Grout",
            "category": "FLOORING",
            "description": "Epoxy/cement grout for tile joints",
            "unit": "kg",
            "specifications": "Various colors",
            "rate_min": 80,
            "rate_max": 250,
            "brands": [
                {"name": "Roff Epoxy", "rate": 220, "grade": "Premium"},
                {"name": "MYK Spectra", "rate": 180, "grade": "Premium"},
                {"name": "Ardex Grout", "rate": 150, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 10,
        },
    ]
    materials.extend(flooring_materials)
    
    # ==================== PAINTS & COATINGS ====================
    paint_materials = [
        {
            "item_name": "Exterior Emulsion Paint",
            "category": "PAINTING",
            "description": "Exterior grade emulsion paint",
            "unit": "ltr",
            "specifications": "Weatherproof, 5+ years warranty",
            "rate_min": 200,
            "rate_max": 500,
            "brands": [
                {"name": "Asian Apex Ultima", "rate": 450, "grade": "Premium"},
                {"name": "Berger Weathercoat", "rate": 420, "grade": "Premium"},
                {"name": "Nerolac Excel", "rate": 400, "grade": "Premium"},
                {"name": "Dulux Weathershield", "rate": 480, "grade": "Luxury"},
                {"name": "Asian Ace Exterior", "rate": 350, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "Interior Emulsion Paint",
            "category": "PAINTING",
            "description": "Interior grade emulsion paint",
            "unit": "ltr",
            "specifications": "Low VOC, washable",
            "rate_min": 150,
            "rate_max": 400,
            "brands": [
                {"name": "Asian Royale", "rate": 380, "grade": "Premium"},
                {"name": "Berger Silk", "rate": 350, "grade": "Premium"},
                {"name": "Nerolac Beauty", "rate": 320, "grade": "Premium"},
                {"name": "Dulux Velvet Touch", "rate": 400, "grade": "Luxury"},
                {"name": "Asian Tractor", "rate": 200, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "Primer (Interior/Exterior)",
            "category": "PAINTING",
            "description": "Base primer for walls",
            "unit": "ltr",
            "specifications": "Water/solvent based primer",
            "rate_min": 100,
            "rate_max": 250,
            "brands": [
                {"name": "Asian Trucare", "rate": 200, "grade": "Premium"},
                {"name": "Berger Primer", "rate": 180, "grade": "Standard"},
                {"name": "Nerolac Primer", "rate": 170, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "Wall Putty",
            "category": "PAINTING",
            "description": "White cement based wall putty",
            "unit": "bag",
            "specifications": "40kg bag, white",
            "rate_min": 650,
            "rate_max": 950,
            "brands": [
                {"name": "Birla White Wallcare", "rate": 900, "grade": "Premium"},
                {"name": "JK Wall Putty", "rate": 850, "grade": "Premium"},
                {"name": "Asian Trucare Putty", "rate": 800, "grade": "Standard"},
                {"name": "Berger Homeshield", "rate": 780, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "POP (Plaster of Paris)",
            "category": "PAINTING",
            "description": "Plaster of Paris for ceiling and walls",
            "unit": "bag",
            "specifications": "25kg bag",
            "rate_min": 350,
            "rate_max": 500,
            "brands": [
                {"name": "JK POP", "rate": 450, "grade": "Premium"},
                {"name": "Birla POP", "rate": 420, "grade": "Premium"},
                {"name": "Local POP", "rate": 380, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 8,
        },
        {
            "item_name": "Gypsum Plaster",
            "category": "PAINTING",
            "description": "Ready-mix gypsum plaster",
            "unit": "bag",
            "specifications": "25kg bag",
            "rate_min": 400,
            "rate_max": 600,
            "brands": [
                {"name": "Saint Gobain Gyproc", "rate": 550, "grade": "Premium"},
                {"name": "USG Boral", "rate": 520, "grade": "Premium"},
                {"name": "Knauf Gypsum", "rate": 500, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Enamel Paint",
            "category": "PAINTING",
            "description": "Synthetic enamel for metal/wood",
            "unit": "ltr",
            "specifications": "High gloss finish",
            "rate_min": 200,
            "rate_max": 450,
            "brands": [
                {"name": "Asian Apcolite", "rate": 400, "grade": "Premium"},
                {"name": "Berger Luxol", "rate": 380, "grade": "Premium"},
                {"name": "Nerolac Enamel", "rate": 350, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "Wood Finish/Melamine",
            "category": "PAINTING",
            "description": "Clear wood finish melamine",
            "unit": "ltr",
            "specifications": "NC/PU finish, clear/tinted",
            "rate_min": 300,
            "rate_max": 700,
            "brands": [
                {"name": "Asian WoodTech", "rate": 600, "grade": "Premium"},
                {"name": "Berger Wood Keeper", "rate": 550, "grade": "Premium"},
                {"name": "Sirca PU", "rate": 650, "grade": "Luxury"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 15,
        },
        {
            "item_name": "Texture Paint",
            "category": "PAINTING",
            "description": "Decorative texture paint",
            "unit": "kg",
            "specifications": "Various textures",
            "rate_min": 150,
            "rate_max": 400,
            "brands": [
                {"name": "Asian Texture", "rate": 350, "grade": "Premium"},
                {"name": "Berger Easy Clean", "rate": 320, "grade": "Premium"},
                {"name": "Nerolac Texture", "rate": 280, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 10,
        },
    ]
    materials.extend(paint_materials)
    
    # ==================== PLUMBING MATERIALS ====================
    plumbing_materials = [
        {
            "item_name": "CPVC Pipes 1/2 inch",
            "category": "PLUMBING",
            "description": "CPVC hot & cold water pipes",
            "unit": "rft",
            "specifications": "SDR 11, 15mm",
            "rate_min": 35,
            "rate_max": 60,
            "brands": [
                {"name": "Ashirvad", "rate": 55, "grade": "Premium"},
                {"name": "Supreme", "rate": 52, "grade": "Premium"},
                {"name": "Prince", "rate": 48, "grade": "Standard"},
                {"name": "Astral", "rate": 50, "grade": "Premium"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "CPVC Pipes 3/4 inch",
            "category": "PLUMBING",
            "description": "CPVC hot & cold water pipes",
            "unit": "rft",
            "specifications": "SDR 11, 20mm",
            "rate_min": 50,
            "rate_max": 80,
            "brands": [
                {"name": "Ashirvad", "rate": 72, "grade": "Premium"},
                {"name": "Supreme", "rate": 68, "grade": "Premium"},
                {"name": "Prince", "rate": 62, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "CPVC Pipes 1 inch",
            "category": "PLUMBING",
            "description": "CPVC hot & cold water pipes for main lines",
            "unit": "rft",
            "specifications": "SDR 11, 25mm",
            "rate_min": 70,
            "rate_max": 110,
            "brands": [
                {"name": "Ashirvad", "rate": 100, "grade": "Premium"},
                {"name": "Supreme", "rate": 95, "grade": "Premium"},
                {"name": "Astral", "rate": 98, "grade": "Premium"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "PVC Drainage Pipes 4 inch",
            "category": "PLUMBING",
            "description": "SWR PVC pipes for drainage",
            "unit": "rft",
            "specifications": "IS 13592, 110mm Type A",
            "rate_min": 70,
            "rate_max": 120,
            "brands": [
                {"name": "Supreme", "rate": 105, "grade": "Premium"},
                {"name": "Astral", "rate": 100, "grade": "Premium"},
                {"name": "Prince", "rate": 90, "grade": "Standard"},
                {"name": "Finolex", "rate": 85, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "PVC Drainage Pipes 6 inch",
            "category": "PLUMBING",
            "description": "SWR PVC pipes for main drainage",
            "unit": "rft",
            "specifications": "IS 13592, 160mm Type A",
            "rate_min": 120,
            "rate_max": 180,
            "brands": [
                {"name": "Supreme", "rate": 165, "grade": "Premium"},
                {"name": "Astral", "rate": 155, "grade": "Premium"},
                {"name": "Prince", "rate": 140, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "GI Pipes 1 inch",
            "category": "PLUMBING",
            "description": "Galvanized iron pipes for water",
            "unit": "rft",
            "specifications": "Medium class, 25mm",
            "rate_min": 80,
            "rate_max": 120,
            "brands": [
                {"name": "TATA", "rate": 110, "grade": "Premium"},
                {"name": "Jindal", "rate": 100, "grade": "Standard"},
                {"name": "APL Apollo", "rate": 105, "grade": "Premium"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Water Tank (Overhead) 1000L",
            "category": "PLUMBING",
            "description": "Plastic overhead water tank",
            "unit": "nos",
            "specifications": "Triple layer, 1000 liters",
            "rate_min": 5000,
            "rate_max": 8000,
            "brands": [
                {"name": "Sintex", "rate": 7500, "grade": "Premium"},
                {"name": "Supreme", "rate": 7000, "grade": "Premium"},
                {"name": "Penguin", "rate": 6500, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "Water Tank (Underground) 5000L",
            "category": "PLUMBING",
            "description": "RCC/FRP underground sump",
            "unit": "nos",
            "specifications": "5000 liters capacity",
            "rate_min": 25000,
            "rate_max": 45000,
            "brands": [
                {"name": "RCC Cast in-situ", "rate": 35000, "grade": "Standard"},
                {"name": "Precast RCC", "rate": 40000, "grade": "Premium"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "CP Basin Mixer",
            "category": "PLUMBING",
            "description": "Chrome plated basin mixer tap",
            "unit": "nos",
            "specifications": "Single lever, hot/cold",
            "rate_min": 2000,
            "rate_max": 15000,
            "brands": [
                {"name": "Jaquar", "rate": 8000, "grade": "Premium"},
                {"name": "Kohler", "rate": 12000, "grade": "Luxury"},
                {"name": "Hindware", "rate": 5000, "grade": "Standard"},
                {"name": "Parryware", "rate": 3500, "grade": "Standard"},
                {"name": "Cera", "rate": 4000, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "Shower Mixer with Diverter",
            "category": "PLUMBING",
            "description": "Wall mounted shower mixer",
            "unit": "nos",
            "specifications": "Hot/cold with diverter",
            "rate_min": 3000,
            "rate_max": 20000,
            "brands": [
                {"name": "Jaquar", "rate": 12000, "grade": "Premium"},
                {"name": "Kohler", "rate": 18000, "grade": "Luxury"},
                {"name": "Hindware", "rate": 6000, "grade": "Standard"},
                {"name": "Grohe", "rate": 15000, "grade": "Luxury"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "Kitchen Sink Mixer",
            "category": "PLUMBING",
            "description": "Single lever kitchen mixer",
            "unit": "nos",
            "specifications": "Swivel spout, pull-out optional",
            "rate_min": 2500,
            "rate_max": 15000,
            "brands": [
                {"name": "Jaquar", "rate": 8000, "grade": "Premium"},
                {"name": "Franke", "rate": 12000, "grade": "Luxury"},
                {"name": "Hindware", "rate": 4500, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "Floor Trap/Drain",
            "category": "PLUMBING",
            "description": "SS/CP floor drain",
            "unit": "nos",
            "specifications": "5x5 inch with trap",
            "rate_min": 150,
            "rate_max": 800,
            "brands": [
                {"name": "Jaquar", "rate": 600, "grade": "Premium"},
                {"name": "Hindware", "rate": 400, "grade": "Standard"},
                {"name": "Local SS", "rate": 200, "grade": "Economy"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
    ]
    materials.extend(plumbing_materials)
    
    # ==================== ELECTRICAL MATERIALS ====================
    electrical_materials = [
        {
            "item_name": "Electrical Wires 1.5 sqmm",
            "category": "ELECTRICAL",
            "description": "FR PVC insulated copper wire",
            "unit": "mtr",
            "specifications": "IS 694, 1.5 sqmm, FR grade",
            "rate_min": 12,
            "rate_max": 22,
            "brands": [
                {"name": "Havells Lifeline", "rate": 20, "grade": "Premium"},
                {"name": "Polycab", "rate": 19, "grade": "Premium"},
                {"name": "Finolex", "rate": 18, "grade": "Premium"},
                {"name": "RR Kabel", "rate": 17, "grade": "Standard"},
                {"name": "V-Guard", "rate": 16, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Electrical Wires 2.5 sqmm",
            "category": "ELECTRICAL",
            "description": "FR PVC insulated copper wire",
            "unit": "mtr",
            "specifications": "IS 694, 2.5 sqmm, FR grade",
            "rate_min": 18,
            "rate_max": 32,
            "brands": [
                {"name": "Havells Lifeline", "rate": 30, "grade": "Premium"},
                {"name": "Polycab", "rate": 28, "grade": "Premium"},
                {"name": "Finolex", "rate": 26, "grade": "Premium"},
                {"name": "RR Kabel", "rate": 24, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Electrical Wires 4 sqmm",
            "category": "ELECTRICAL",
            "description": "FR PVC insulated copper wire for AC/Geyser",
            "unit": "mtr",
            "specifications": "IS 694, 4 sqmm, FR grade",
            "rate_min": 28,
            "rate_max": 48,
            "brands": [
                {"name": "Havells Lifeline", "rate": 45, "grade": "Premium"},
                {"name": "Polycab", "rate": 42, "grade": "Premium"},
                {"name": "Finolex", "rate": 40, "grade": "Premium"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Electrical Wires 6 sqmm",
            "category": "ELECTRICAL",
            "description": "FR PVC insulated copper wire for main lines",
            "unit": "mtr",
            "specifications": "IS 694, 6 sqmm, FR grade",
            "rate_min": 42,
            "rate_max": 68,
            "brands": [
                {"name": "Havells Lifeline", "rate": 65, "grade": "Premium"},
                {"name": "Polycab", "rate": 60, "grade": "Premium"},
                {"name": "Finolex", "rate": 55, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "PVC Conduit Pipes 20mm",
            "category": "ELECTRICAL",
            "description": "Heavy duty PVC conduit",
            "unit": "mtr",
            "specifications": "IS 9537, 20mm, heavy gauge",
            "rate_min": 12,
            "rate_max": 25,
            "brands": [
                {"name": "Precision", "rate": 22, "grade": "Premium"},
                {"name": "Sudhakar", "rate": 20, "grade": "Premium"},
                {"name": "Finolex", "rate": 18, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "PVC Conduit Pipes 25mm",
            "category": "ELECTRICAL",
            "description": "Heavy duty PVC conduit for main runs",
            "unit": "mtr",
            "specifications": "IS 9537, 25mm, heavy gauge",
            "rate_min": 18,
            "rate_max": 32,
            "brands": [
                {"name": "Precision", "rate": 28, "grade": "Premium"},
                {"name": "Sudhakar", "rate": 25, "grade": "Premium"},
                {"name": "Finolex", "rate": 22, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Modular Switches (6A)",
            "category": "ELECTRICAL",
            "description": "Modular switches 6 Amp",
            "unit": "nos",
            "specifications": "1 Module, 6A rated",
            "rate_min": 40,
            "rate_max": 150,
            "brands": [
                {"name": "Legrand", "rate": 120, "grade": "Premium"},
                {"name": "Havells", "rate": 100, "grade": "Premium"},
                {"name": "Anchor Roma", "rate": 80, "grade": "Standard"},
                {"name": "GM", "rate": 60, "grade": "Standard"},
                {"name": "Schneider", "rate": 130, "grade": "Luxury"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 2,
        },
        {
            "item_name": "Modular Switches (16A)",
            "category": "ELECTRICAL",
            "description": "Modular switches 16 Amp for AC/Geyser",
            "unit": "nos",
            "specifications": "2 Module, 16A rated",
            "rate_min": 80,
            "rate_max": 250,
            "brands": [
                {"name": "Legrand", "rate": 200, "grade": "Premium"},
                {"name": "Havells", "rate": 180, "grade": "Premium"},
                {"name": "Anchor Roma", "rate": 140, "grade": "Standard"},
                {"name": "Schneider", "rate": 220, "grade": "Luxury"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 2,
        },
        {
            "item_name": "Modular Socket 5/6A",
            "category": "ELECTRICAL",
            "description": "5/6 Amp socket outlet",
            "unit": "nos",
            "specifications": "2 Module, 5/6A",
            "rate_min": 50,
            "rate_max": 180,
            "brands": [
                {"name": "Legrand", "rate": 150, "grade": "Premium"},
                {"name": "Havells", "rate": 130, "grade": "Premium"},
                {"name": "Anchor", "rate": 100, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 2,
        },
        {
            "item_name": "Modular Socket 16A",
            "category": "ELECTRICAL",
            "description": "16 Amp socket for AC/Geyser",
            "unit": "nos",
            "specifications": "3 Module, 16A",
            "rate_min": 100,
            "rate_max": 300,
            "brands": [
                {"name": "Legrand", "rate": 250, "grade": "Premium"},
                {"name": "Havells", "rate": 220, "grade": "Premium"},
                {"name": "Anchor", "rate": 160, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 2,
        },
        {
            "item_name": "MCB Single Pole",
            "category": "ELECTRICAL",
            "description": "Miniature Circuit Breaker SP",
            "unit": "nos",
            "specifications": "6-32A, 10kA breaking",
            "rate_min": 120,
            "rate_max": 350,
            "brands": [
                {"name": "Havells", "rate": 280, "grade": "Premium"},
                {"name": "Legrand", "rate": 300, "grade": "Premium"},
                {"name": "Schneider", "rate": 320, "grade": "Luxury"},
                {"name": "ABB", "rate": 340, "grade": "Luxury"},
                {"name": "Anchor", "rate": 180, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "MCB Double Pole",
            "category": "ELECTRICAL",
            "description": "Miniature Circuit Breaker DP",
            "unit": "nos",
            "specifications": "16-40A, 10kA breaking",
            "rate_min": 300,
            "rate_max": 700,
            "brands": [
                {"name": "Havells", "rate": 550, "grade": "Premium"},
                {"name": "Legrand", "rate": 600, "grade": "Premium"},
                {"name": "Schneider", "rate": 650, "grade": "Luxury"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "RCCB 40A 30mA",
            "category": "ELECTRICAL",
            "description": "Residual Current Circuit Breaker",
            "unit": "nos",
            "specifications": "40A, 30mA sensitivity",
            "rate_min": 1500,
            "rate_max": 3500,
            "brands": [
                {"name": "Havells", "rate": 2800, "grade": "Premium"},
                {"name": "Legrand", "rate": 3000, "grade": "Premium"},
                {"name": "Schneider", "rate": 3200, "grade": "Luxury"},
                {"name": "ABB", "rate": 3400, "grade": "Luxury"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "Distribution Board 8 Way",
            "category": "ELECTRICAL",
            "description": "MCB distribution board",
            "unit": "nos",
            "specifications": "8 way SPN DB",
            "rate_min": 800,
            "rate_max": 2000,
            "brands": [
                {"name": "Havells", "rate": 1600, "grade": "Premium"},
                {"name": "Legrand", "rate": 1800, "grade": "Premium"},
                {"name": "Schneider", "rate": 1900, "grade": "Luxury"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "Distribution Board 12 Way",
            "category": "ELECTRICAL",
            "description": "MCB distribution board",
            "unit": "nos",
            "specifications": "12 way TPN DB",
            "rate_min": 1500,
            "rate_max": 3500,
            "brands": [
                {"name": "Havells", "rate": 2800, "grade": "Premium"},
                {"name": "Legrand", "rate": 3000, "grade": "Premium"},
                {"name": "Schneider", "rate": 3200, "grade": "Luxury"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "Ceiling Fan Regulator",
            "category": "ELECTRICAL",
            "description": "Electronic fan regulator",
            "unit": "nos",
            "specifications": "5 step electronic",
            "rate_min": 150,
            "rate_max": 450,
            "brands": [
                {"name": "Havells", "rate": 380, "grade": "Premium"},
                {"name": "Anchor", "rate": 280, "grade": "Standard"},
                {"name": "GM", "rate": 220, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 2,
        },
        {
            "item_name": "LED Panel Light 18W",
            "category": "ELECTRICAL",
            "description": "Surface/recessed LED panel",
            "unit": "nos",
            "specifications": "18W, 6500K/3000K",
            "rate_min": 350,
            "rate_max": 800,
            "brands": [
                {"name": "Philips", "rate": 700, "grade": "Premium"},
                {"name": "Havells", "rate": 650, "grade": "Premium"},
                {"name": "Syska", "rate": 500, "grade": "Standard"},
                {"name": "Crompton", "rate": 480, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "LED Downlight 15W",
            "category": "ELECTRICAL",
            "description": "Recessed LED downlight",
            "unit": "nos",
            "specifications": "15W, 4 inch cut-out",
            "rate_min": 300,
            "rate_max": 700,
            "brands": [
                {"name": "Philips", "rate": 600, "grade": "Premium"},
                {"name": "Havells", "rate": 550, "grade": "Premium"},
                {"name": "Syska", "rate": 420, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 0,
        },
    ]
    materials.extend(electrical_materials)
    
    # ==================== WATERPROOFING & INSULATION ====================
    waterproofing_materials = [
        {
            "item_name": "APP Membrane Waterproofing",
            "category": "WATERPROOFING",
            "description": "APP modified bitumen membrane",
            "unit": "sqm",
            "specifications": "3mm thick, torch applied",
            "rate_min": 80,
            "rate_max": 150,
            "brands": [
                {"name": "Dr. Fixit", "rate": 130, "grade": "Premium"},
                {"name": "BASF MasterSeal", "rate": 140, "grade": "Premium"},
                {"name": "Sika", "rate": 135, "grade": "Premium"},
                {"name": "Fosroc", "rate": 125, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "Liquid Waterproofing Membrane",
            "category": "WATERPROOFING",
            "description": "Acrylic liquid applied membrane",
            "unit": "sqm",
            "specifications": "2 coat application",
            "rate_min": 60,
            "rate_max": 120,
            "brands": [
                {"name": "Dr. Fixit Roofseal", "rate": 100, "grade": "Premium"},
                {"name": "Asian Damp Proof", "rate": 90, "grade": "Standard"},
                {"name": "Sika Textop", "rate": 110, "grade": "Premium"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "Integral Waterproofing Compound",
            "category": "WATERPROOFING",
            "description": "Waterproofing admixture for concrete",
            "unit": "kg",
            "specifications": "1% by weight of cement",
            "rate_min": 40,
            "rate_max": 80,
            "brands": [
                {"name": "Dr. Fixit Pidiproof LW+", "rate": 70, "grade": "Premium"},
                {"name": "Sika Latex", "rate": 75, "grade": "Premium"},
                {"name": "Fosroc Conplast", "rate": 65, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Bathroom Waterproofing",
            "category": "WATERPROOFING",
            "description": "Bathroom waterproofing system",
            "unit": "sqft",
            "specifications": "Cementitious coating + membrane",
            "rate_min": 40,
            "rate_max": 80,
            "brands": [
                {"name": "Dr. Fixit Bathseal", "rate": 70, "grade": "Premium"},
                {"name": "Sika Topseal 107", "rate": 75, "grade": "Premium"},
                {"name": "BASF", "rate": 65, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "Terrace Waterproofing (Complete)",
            "category": "WATERPROOFING",
            "description": "Complete terrace waterproofing treatment",
            "unit": "sqft",
            "specifications": "Membrane + screed + tiles",
            "rate_min": 80,
            "rate_max": 150,
            "brands": [
                {"name": "Dr. Fixit System", "rate": 130, "grade": "Premium"},
                {"name": "Sika System", "rate": 140, "grade": "Premium"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Thermal Insulation - XPS Board",
            "category": "WATERPROOFING",
            "description": "Extruded polystyrene insulation",
            "unit": "sqft",
            "specifications": "25mm thick, 35 kg/m³ density",
            "rate_min": 30,
            "rate_max": 60,
            "brands": [
                {"name": "Supreme Ecotherm", "rate": 50, "grade": "Premium"},
                {"name": "Dow Styrofoam", "rate": 55, "grade": "Premium"},
                {"name": "Local XPS", "rate": 35, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Thermal Insulation - Rockwool",
            "category": "WATERPROOFING",
            "description": "Mineral wool insulation for walls/roof",
            "unit": "sqft",
            "specifications": "50mm thick, 48-96 kg/m³",
            "rate_min": 25,
            "rate_max": 50,
            "brands": [
                {"name": "Rockwool", "rate": 45, "grade": "Premium"},
                {"name": "Lloyd Insulations", "rate": 40, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 5,
        },
    ]
    materials.extend(waterproofing_materials)
    
    # ==================== DOORS & WINDOWS ====================
    doors_windows_materials = [
        {
            "item_name": "Main Door Frame (Teak)",
            "category": "DOORS_WINDOWS",
            "description": "Solid teak wood door frame",
            "unit": "rft",
            "specifications": "5x3 inch, seasoned teak",
            "rate_min": 500,
            "rate_max": 1200,
            "brands": [
                {"name": "Burma Teak", "rate": 1100, "grade": "Luxury"},
                {"name": "CP Teak", "rate": 800, "grade": "Premium"},
                {"name": "Nilambur Teak", "rate": 700, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "Internal Door Frame (Sal Wood)",
            "category": "DOORS_WINDOWS",
            "description": "Sal wood door frame for internal doors",
            "unit": "rft",
            "specifications": "4x2.5 inch, seasoned",
            "rate_min": 200,
            "rate_max": 400,
            "brands": [
                {"name": "Grade I Sal", "rate": 350, "grade": "Premium"},
                {"name": "Grade II Sal", "rate": 280, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "Flush Door (Commercial)",
            "category": "DOORS_WINDOWS",
            "description": "Commercial grade flush door",
            "unit": "sqft",
            "specifications": "30mm thick, BWR grade",
            "rate_min": 45,
            "rate_max": 90,
            "brands": [
                {"name": "Greenply", "rate": 75, "grade": "Premium"},
                {"name": "Century", "rate": 70, "grade": "Premium"},
                {"name": "Kitply", "rate": 60, "grade": "Standard"},
                {"name": "National", "rate": 55, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Flush Door (Decorative)",
            "category": "DOORS_WINDOWS",
            "description": "Decorative flush door with veneer/laminate",
            "unit": "sqft",
            "specifications": "32-35mm thick, decorative face",
            "rate_min": 80,
            "rate_max": 200,
            "brands": [
                {"name": "Greenply Ekotec", "rate": 150, "grade": "Premium"},
                {"name": "Century Sainik", "rate": 140, "grade": "Premium"},
                {"name": "Merino Laminated", "rate": 180, "grade": "Luxury"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Solid Panel Door (Teak)",
            "category": "DOORS_WINDOWS",
            "description": "Solid teak wood panel door",
            "unit": "sqft",
            "specifications": "4 panel design, seasoned teak",
            "rate_min": 400,
            "rate_max": 800,
            "brands": [
                {"name": "Burma Teak", "rate": 750, "grade": "Luxury"},
                {"name": "CP Teak", "rate": 550, "grade": "Premium"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "UPVC Window (White)",
            "category": "DOORS_WINDOWS",
            "description": "UPVC sliding/casement window",
            "unit": "sqft",
            "specifications": "60mm profile, 5mm glass",
            "rate_min": 350,
            "rate_max": 600,
            "brands": [
                {"name": "Fenesta", "rate": 550, "grade": "Premium"},
                {"name": "Encraft", "rate": 500, "grade": "Premium"},
                {"name": "NCL VEKA", "rate": 480, "grade": "Standard"},
                {"name": "Lingel", "rate": 420, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Aluminium Window (Powder Coated)",
            "category": "DOORS_WINDOWS",
            "description": "Aluminium sliding window",
            "unit": "sqft",
            "specifications": "Standard section, 5mm glass",
            "rate_min": 280,
            "rate_max": 450,
            "brands": [
                {"name": "Jindal", "rate": 400, "grade": "Premium"},
                {"name": "Hindalco", "rate": 380, "grade": "Premium"},
                {"name": "Local Fabricated", "rate": 300, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "MS Window Grills",
            "category": "DOORS_WINDOWS",
            "description": "Mild steel window grills",
            "unit": "sqft",
            "specifications": "16mm square bar, powder coated",
            "rate_min": 80,
            "rate_max": 180,
            "brands": [
                {"name": "Designer Pattern", "rate": 150, "grade": "Premium"},
                {"name": "Standard Pattern", "rate": 100, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "SS Safety Door",
            "category": "DOORS_WINDOWS",
            "description": "Stainless steel safety door",
            "unit": "sqft",
            "specifications": "SS 304 grade, designer",
            "rate_min": 400,
            "rate_max": 800,
            "brands": [
                {"name": "Salem Steel", "rate": 700, "grade": "Premium"},
                {"name": "Local Fabricated 304", "rate": 550, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 5,
        },
    ]
    materials.extend(doors_windows_materials)
    
    # ==================== HARDWARE & FITTINGS ====================
    hardware_materials = [
        {
            "item_name": "Door Lock Set (Mortise)",
            "category": "HARDWARE",
            "description": "Mortise door lock with handles",
            "unit": "set",
            "specifications": "7 lever, SS finish",
            "rate_min": 800,
            "rate_max": 5000,
            "brands": [
                {"name": "Godrej", "rate": 3500, "grade": "Premium"},
                {"name": "Yale", "rate": 4000, "grade": "Luxury"},
                {"name": "Dorset", "rate": 2500, "grade": "Standard"},
                {"name": "Europa", "rate": 2000, "grade": "Standard"},
                {"name": "Link", "rate": 1200, "grade": "Economy"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "Door Hinges (SS)",
            "category": "HARDWARE",
            "description": "Stainless steel butt hinges",
            "unit": "pair",
            "specifications": "5 inch, SS 304",
            "rate_min": 150,
            "rate_max": 500,
            "brands": [
                {"name": "Dorma", "rate": 400, "grade": "Premium"},
                {"name": "Ozone", "rate": 350, "grade": "Premium"},
                {"name": "Dorset", "rate": 250, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "Tower Bolt (SS)",
            "category": "HARDWARE",
            "description": "Stainless steel tower bolt",
            "unit": "nos",
            "specifications": "8-12 inch, SS 304",
            "rate_min": 100,
            "rate_max": 300,
            "brands": [
                {"name": "Ozone", "rate": 250, "grade": "Premium"},
                {"name": "Dorset", "rate": 180, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "Door Closer (Hydraulic)",
            "category": "HARDWARE",
            "description": "Hydraulic door closer",
            "unit": "nos",
            "specifications": "80-120kg door weight",
            "rate_min": 800,
            "rate_max": 3000,
            "brands": [
                {"name": "Dorma", "rate": 2500, "grade": "Premium"},
                {"name": "Ozone", "rate": 2000, "grade": "Premium"},
                {"name": "Godrej", "rate": 1500, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "Digital Door Lock",
            "category": "HARDWARE",
            "description": "Smart digital door lock",
            "unit": "nos",
            "specifications": "Fingerprint/PIN/Card/Key",
            "rate_min": 8000,
            "rate_max": 35000,
            "brands": [
                {"name": "Yale", "rate": 25000, "grade": "Luxury"},
                {"name": "Samsung", "rate": 30000, "grade": "Luxury"},
                {"name": "Godrej", "rate": 15000, "grade": "Premium"},
                {"name": "Ozone", "rate": 12000, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "Bathroom Door Lock",
            "category": "HARDWARE",
            "description": "Privacy lock for bathroom",
            "unit": "nos",
            "specifications": "Baby latch type, SS finish",
            "rate_min": 300,
            "rate_max": 1200,
            "brands": [
                {"name": "Dorset", "rate": 900, "grade": "Premium"},
                {"name": "Europa", "rate": 700, "grade": "Standard"},
                {"name": "Link", "rate": 450, "grade": "Economy"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
    ]
    materials.extend(hardware_materials)
    
    # ==================== WOOD & PLYWOOD ====================
    wood_materials = [
        {
            "item_name": "Commercial Plywood 18mm",
            "category": "WOOD",
            "description": "Commercial grade plywood",
            "unit": "sqft",
            "specifications": "18mm, MR grade",
            "rate_min": 40,
            "rate_max": 75,
            "brands": [
                {"name": "Greenply", "rate": 65, "grade": "Premium"},
                {"name": "Century", "rate": 60, "grade": "Premium"},
                {"name": "Kitply", "rate": 52, "grade": "Standard"},
                {"name": "National", "rate": 48, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "BWR Plywood 19mm",
            "category": "WOOD",
            "description": "Boiling Water Resistant plywood",
            "unit": "sqft",
            "specifications": "19mm, BWR grade",
            "rate_min": 55,
            "rate_max": 100,
            "brands": [
                {"name": "Greenply Club", "rate": 85, "grade": "Premium"},
                {"name": "Century Club Prime", "rate": 80, "grade": "Premium"},
                {"name": "Archid BWR", "rate": 70, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "Marine Plywood 19mm",
            "category": "WOOD",
            "description": "Marine grade plywood for wet areas",
            "unit": "sqft",
            "specifications": "19mm, IS 710 Grade",
            "rate_min": 80,
            "rate_max": 140,
            "brands": [
                {"name": "Greenply Marine", "rate": 120, "grade": "Premium"},
                {"name": "Century Marine", "rate": 115, "grade": "Premium"},
                {"name": "Archid Marine", "rate": 100, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "Block Board 19mm",
            "category": "WOOD",
            "description": "Block board for furniture",
            "unit": "sqft",
            "specifications": "19mm thick",
            "rate_min": 50,
            "rate_max": 90,
            "brands": [
                {"name": "Greenply", "rate": 75, "grade": "Premium"},
                {"name": "Century", "rate": 70, "grade": "Premium"},
                {"name": "Kitply", "rate": 60, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "MDF Board 18mm",
            "category": "WOOD",
            "description": "Medium Density Fibreboard",
            "unit": "sqft",
            "specifications": "18mm, plain/prelaminated",
            "rate_min": 35,
            "rate_max": 65,
            "brands": [
                {"name": "Action Tesa", "rate": 55, "grade": "Premium"},
                {"name": "Greenply", "rate": 52, "grade": "Premium"},
                {"name": "Century", "rate": 50, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "HDHMR Board 18mm",
            "category": "WOOD",
            "description": "High Density High Moisture Resistant",
            "unit": "sqft",
            "specifications": "18mm, prelaminated",
            "rate_min": 45,
            "rate_max": 80,
            "brands": [
                {"name": "Action Tesa", "rate": 70, "grade": "Premium"},
                {"name": "Greenply", "rate": 65, "grade": "Premium"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "Decorative Laminate",
            "category": "WOOD",
            "description": "High pressure decorative laminate",
            "unit": "sqft",
            "specifications": "1mm thick, various finishes",
            "rate_min": 20,
            "rate_max": 80,
            "brands": [
                {"name": "Merino", "rate": 55, "grade": "Premium"},
                {"name": "Greenlam", "rate": 50, "grade": "Premium"},
                {"name": "Century", "rate": 45, "grade": "Standard"},
                {"name": "Virgo", "rate": 40, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 15,
        },
        {
            "item_name": "Veneer (Natural)",
            "category": "WOOD",
            "description": "Natural wood veneer",
            "unit": "sqft",
            "specifications": "0.5mm, various species",
            "rate_min": 30,
            "rate_max": 150,
            "brands": [
                {"name": "Teak Veneer", "rate": 120, "grade": "Premium"},
                {"name": "Oak Veneer", "rate": 100, "grade": "Premium"},
                {"name": "Walnut Veneer", "rate": 80, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 15,
        },
    ]
    materials.extend(wood_materials)
    
    # ==================== KITCHEN & SANITARY ====================
    kitchen_sanitary_materials = [
        {
            "item_name": "Kitchen Sink (SS)",
            "category": "KITCHEN",
            "description": "Stainless steel kitchen sink",
            "unit": "nos",
            "specifications": "Double bowl, 304 grade",
            "rate_min": 3000,
            "rate_max": 15000,
            "brands": [
                {"name": "Franke", "rate": 12000, "grade": "Luxury"},
                {"name": "Nirali", "rate": 8000, "grade": "Premium"},
                {"name": "Carysil", "rate": 10000, "grade": "Premium"},
                {"name": "Hindware", "rate": 6000, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "Granite Kitchen Counter",
            "category": "KITCHEN",
            "description": "Granite counter top for kitchen",
            "unit": "sqft",
            "specifications": "20mm thick, polished",
            "rate_min": 120,
            "rate_max": 350,
            "brands": [
                {"name": "Black Galaxy", "rate": 300, "grade": "Luxury"},
                {"name": "Steel Grey", "rate": 200, "grade": "Premium"},
                {"name": "Black Pearl", "rate": 180, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "Quartz Kitchen Counter",
            "category": "KITCHEN",
            "description": "Engineered quartz counter top",
            "unit": "sqft",
            "specifications": "20mm thick, various colors",
            "rate_min": 250,
            "rate_max": 600,
            "brands": [
                {"name": "Kalinga Stone", "rate": 450, "grade": "Premium"},
                {"name": "Quantra", "rate": 400, "grade": "Premium"},
                {"name": "Cosentino", "rate": 550, "grade": "Luxury"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "EWC (Western Commode)",
            "category": "KITCHEN",
            "description": "European water closet",
            "unit": "nos",
            "specifications": "Floor mounted, S-trap",
            "rate_min": 4000,
            "rate_max": 25000,
            "brands": [
                {"name": "Kohler", "rate": 20000, "grade": "Luxury"},
                {"name": "TOTO", "rate": 18000, "grade": "Luxury"},
                {"name": "Jaquar", "rate": 12000, "grade": "Premium"},
                {"name": "Hindware", "rate": 8000, "grade": "Standard"},
                {"name": "Parryware", "rate": 6000, "grade": "Standard"},
                {"name": "Cera", "rate": 5000, "grade": "Economy"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "Wall Hung Basin",
            "category": "KITCHEN",
            "description": "Wall mounted wash basin",
            "unit": "nos",
            "specifications": "18-22 inch, white",
            "rate_min": 1500,
            "rate_max": 15000,
            "brands": [
                {"name": "Kohler", "rate": 12000, "grade": "Luxury"},
                {"name": "Jaquar", "rate": 8000, "grade": "Premium"},
                {"name": "Hindware", "rate": 5000, "grade": "Standard"},
                {"name": "Parryware", "rate": 3500, "grade": "Standard"},
                {"name": "Cera", "rate": 2500, "grade": "Economy"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "Pedestal Basin",
            "category": "KITCHEN",
            "description": "Basin with pedestal",
            "unit": "set",
            "specifications": "Full pedestal, 22-24 inch",
            "rate_min": 2000,
            "rate_max": 18000,
            "brands": [
                {"name": "Kohler", "rate": 15000, "grade": "Luxury"},
                {"name": "Jaquar", "rate": 10000, "grade": "Premium"},
                {"name": "Hindware", "rate": 6000, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "Health Faucet",
            "category": "KITCHEN",
            "description": "Hand held bidet spray",
            "unit": "nos",
            "specifications": "With hose and holder",
            "rate_min": 400,
            "rate_max": 2500,
            "brands": [
                {"name": "Jaquar", "rate": 2000, "grade": "Premium"},
                {"name": "Hindware", "rate": 1200, "grade": "Standard"},
                {"name": "Parryware", "rate": 800, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "Shower Set (Overhead)",
            "category": "KITCHEN",
            "description": "Overhead shower with arm",
            "unit": "set",
            "specifications": "8-10 inch, rain shower",
            "rate_min": 1500,
            "rate_max": 12000,
            "brands": [
                {"name": "Kohler", "rate": 10000, "grade": "Luxury"},
                {"name": "Grohe", "rate": 9000, "grade": "Luxury"},
                {"name": "Jaquar", "rate": 6000, "grade": "Premium"},
                {"name": "Hindware", "rate": 3500, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "Bathroom Mirror",
            "category": "KITCHEN",
            "description": "Beveled edge mirror",
            "unit": "sqft",
            "specifications": "5mm thick, beveled",
            "rate_min": 80,
            "rate_max": 200,
            "brands": [
                {"name": "Saint Gobain", "rate": 180, "grade": "Premium"},
                {"name": "Asahi", "rate": 160, "grade": "Premium"},
                {"name": "Modiguard", "rate": 120, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Bathroom Accessories Set",
            "category": "KITCHEN",
            "description": "Complete bathroom accessories",
            "unit": "set",
            "specifications": "Towel rod, soap dish, hooks, etc.",
            "rate_min": 2000,
            "rate_max": 10000,
            "brands": [
                {"name": "Kohler", "rate": 8000, "grade": "Luxury"},
                {"name": "Jaquar", "rate": 6000, "grade": "Premium"},
                {"name": "Hindware", "rate": 4000, "grade": "Standard"},
                {"name": "Cera", "rate": 3000, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
    ]
    materials.extend(kitchen_sanitary_materials)
    
    # ==================== GLASS & GLAZING ====================
    glass_materials = [
        {
            "item_name": "Float Glass 5mm (Clear)",
            "category": "GLASS",
            "description": "Clear float glass for windows",
            "unit": "sqft",
            "specifications": "5mm thick, clear",
            "rate_min": 45,
            "rate_max": 75,
            "brands": [
                {"name": "Saint Gobain", "rate": 65, "grade": "Premium"},
                {"name": "Asahi", "rate": 60, "grade": "Premium"},
                {"name": "Modiguard", "rate": 55, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "Tempered Glass 10mm",
            "category": "GLASS",
            "description": "Toughened safety glass",
            "unit": "sqft",
            "specifications": "10mm, toughened",
            "rate_min": 150,
            "rate_max": 280,
            "brands": [
                {"name": "Saint Gobain", "rate": 250, "grade": "Premium"},
                {"name": "Asahi", "rate": 230, "grade": "Premium"},
                {"name": "Gold Plus", "rate": 200, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Tempered Glass 12mm",
            "category": "GLASS",
            "description": "Toughened safety glass for partitions",
            "unit": "sqft",
            "specifications": "12mm, toughened",
            "rate_min": 180,
            "rate_max": 350,
            "brands": [
                {"name": "Saint Gobain", "rate": 300, "grade": "Premium"},
                {"name": "Asahi", "rate": 280, "grade": "Premium"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "DGU Glass (Double Glazed)",
            "category": "GLASS",
            "description": "Double glazed unit for insulation",
            "unit": "sqft",
            "specifications": "5+12+5mm, argon filled",
            "rate_min": 250,
            "rate_max": 450,
            "brands": [
                {"name": "Saint Gobain", "rate": 400, "grade": "Premium"},
                {"name": "Asahi", "rate": 380, "grade": "Premium"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Frosted Glass",
            "category": "GLASS",
            "description": "Sandblasted/acid etched glass",
            "unit": "sqft",
            "specifications": "5-6mm, frosted finish",
            "rate_min": 80,
            "rate_max": 150,
            "brands": [
                {"name": "Saint Gobain", "rate": 130, "grade": "Premium"},
                {"name": "Asahi", "rate": 120, "grade": "Premium"},
                {"name": "Local Sandblasted", "rate": 90, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 10,
        },
        {
            "item_name": "Lacquered Glass",
            "category": "GLASS",
            "description": "Back painted glass for kitchen/wardrobe",
            "unit": "sqft",
            "specifications": "4-5mm, various colors",
            "rate_min": 100,
            "rate_max": 200,
            "brands": [
                {"name": "Saint Gobain Lacobel", "rate": 180, "grade": "Premium"},
                {"name": "Asahi", "rate": 160, "grade": "Premium"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 10,
        },
    ]
    materials.extend(glass_materials)
    
    # ==================== ROOFING MATERIALS ====================
    roofing_materials = [
        {
            "item_name": "Clay Roof Tiles (Mangalore)",
            "category": "ROOFING",
            "description": "Traditional clay roof tiles",
            "unit": "nos",
            "specifications": "Standard Mangalore pattern",
            "rate_min": 15,
            "rate_max": 35,
            "brands": [
                {"name": "Mangalore Tiles", "rate": 28, "grade": "Premium"},
                {"name": "Local Clay", "rate": 20, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Concrete Roof Tiles",
            "category": "ROOFING",
            "description": "Concrete interlocking roof tiles",
            "unit": "nos",
            "specifications": "Interlocking pattern",
            "rate_min": 40,
            "rate_max": 80,
            "brands": [
                {"name": "BMI Coverland", "rate": 70, "grade": "Premium"},
                {"name": "Pioneer", "rate": 55, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 5,
        },
        {
            "item_name": "Metal Roofing Sheet",
            "category": "ROOFING",
            "description": "Color coated metal roofing",
            "unit": "sqft",
            "specifications": "0.5mm, prepainted",
            "rate_min": 35,
            "rate_max": 65,
            "brands": [
                {"name": "TATA Bluescope", "rate": 58, "grade": "Premium"},
                {"name": "JSW Colouron", "rate": 52, "grade": "Premium"},
                {"name": "Local Coated", "rate": 40, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 8,
        },
        {
            "item_name": "Polycarbonate Sheet",
            "category": "ROOFING",
            "description": "Polycarbonate roofing sheet",
            "unit": "sqft",
            "specifications": "Multi-wall, 6mm thick",
            "rate_min": 60,
            "rate_max": 120,
            "brands": [
                {"name": "Tuflite", "rate": 100, "grade": "Premium"},
                {"name": "Palram", "rate": 95, "grade": "Premium"},
                {"name": "Local", "rate": 70, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 10,
        },
    ]
    materials.extend(roofing_materials)
    
    # ==================== SAFETY & FIRE PROTECTION ====================
    safety_materials = [
        {
            "item_name": "Fire Extinguisher (ABC)",
            "category": "SAFETY",
            "description": "ABC type fire extinguisher",
            "unit": "nos",
            "specifications": "4kg, ISI marked",
            "rate_min": 1500,
            "rate_max": 3000,
            "brands": [
                {"name": "Cease Fire", "rate": 2500, "grade": "Premium"},
                {"name": "Safex", "rate": 2200, "grade": "Premium"},
                {"name": "Minimax", "rate": 2000, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "Smoke Detector",
            "category": "SAFETY",
            "description": "Photoelectric smoke detector",
            "unit": "nos",
            "specifications": "Ceiling mounted, with sounder",
            "rate_min": 800,
            "rate_max": 2500,
            "brands": [
                {"name": "Honeywell", "rate": 2200, "grade": "Premium"},
                {"name": "Bosch", "rate": 2000, "grade": "Premium"},
                {"name": "Agni", "rate": 1200, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "Fire Alarm Panel",
            "category": "SAFETY",
            "description": "Conventional fire alarm panel",
            "unit": "nos",
            "specifications": "4-8 zone",
            "rate_min": 8000,
            "rate_max": 25000,
            "brands": [
                {"name": "Honeywell", "rate": 20000, "grade": "Premium"},
                {"name": "Bosch", "rate": 18000, "grade": "Premium"},
                {"name": "Agni", "rate": 12000, "grade": "Standard"},
            ],
            "is_mandatory": False,
            "typical_wastage_percent": 0,
        },
        {
            "item_name": "Emergency Light",
            "category": "SAFETY",
            "description": "LED emergency light with battery",
            "unit": "nos",
            "specifications": "Twin lamp, 3hr backup",
            "rate_min": 800,
            "rate_max": 2500,
            "brands": [
                {"name": "Philips", "rate": 2200, "grade": "Premium"},
                {"name": "Crompton", "rate": 1800, "grade": "Premium"},
                {"name": "Havells", "rate": 1500, "grade": "Standard"},
            ],
            "is_mandatory": True,
            "typical_wastage_percent": 0,
        },
    ]
    materials.extend(safety_materials)
    
    return materials


def get_preset_templates() -> List[Dict[str, Any]]:
    """
    Returns preset template configurations for different project types
    """
    return [
        {
            "name": "Residential Standard (G+1)",
            "description": "Standard materials for residential G+1 construction",
            "project_type": "residential",
            "region": "Bangalore",
            "categories": ["CEMENT", "STEEL", "AGGREGATES", "MASONRY", "FLOORING", "PAINTING", "PLUMBING", "ELECTRICAL", "WATERPROOFING", "DOORS_WINDOWS", "HARDWARE", "KITCHEN"],
            "quality_preference": "Standard",
        },
        {
            "name": "Residential Premium (G+2)",
            "description": "Premium materials for residential G+2 construction",
            "project_type": "residential",
            "region": "Bangalore",
            "categories": ["CEMENT", "STEEL", "AGGREGATES", "MASONRY", "FLOORING", "PAINTING", "PLUMBING", "ELECTRICAL", "WATERPROOFING", "DOORS_WINDOWS", "HARDWARE", "WOOD", "KITCHEN", "GLASS"],
            "quality_preference": "Premium",
        },
        {
            "name": "Commercial Standard",
            "description": "Standard materials for commercial construction",
            "project_type": "commercial",
            "region": "Bangalore",
            "categories": ["CEMENT", "STEEL", "AGGREGATES", "MASONRY", "FLOORING", "PAINTING", "PLUMBING", "ELECTRICAL", "WATERPROOFING", "DOORS_WINDOWS", "GLASS", "SAFETY"],
            "quality_preference": "Standard",
        },
        {
            "name": "Villa Luxury",
            "description": "Luxury materials for villa construction",
            "project_type": "villa",
            "region": "Bangalore",
            "categories": list(CATEGORIES.keys()),
            "quality_preference": "Luxury",
        },
        {
            "name": "Apartment Complex",
            "description": "Materials for apartment complex construction",
            "project_type": "apartment",
            "region": "Bangalore",
            "categories": ["CEMENT", "STEEL", "AGGREGATES", "MASONRY", "FLOORING", "PAINTING", "PLUMBING", "ELECTRICAL", "WATERPROOFING", "DOORS_WINDOWS", "HARDWARE", "KITCHEN", "SAFETY"],
            "quality_preference": "Standard",
        },
    ]


def filter_materials_by_template(materials: List[Dict], template: Dict) -> List[Dict]:
    """
    Filter materials based on template configuration
    """
    filtered = []
    categories = template.get("categories", [])
    quality = template.get("quality_preference", "Standard")
    
    for material in materials:
        if material["category"] in categories:
            # Filter brands by quality preference
            if "brands" in material:
                quality_order = ["Economy", "Standard", "Premium", "Luxury"]
                target_idx = quality_order.index(quality) if quality in quality_order else 1
                
                filtered_brands = []
                for brand in material["brands"]:
                    brand_quality = brand.get("grade", "Standard")
                    brand_idx = quality_order.index(brand_quality) if brand_quality in quality_order else 1
                    
                    # Include brands at or above the quality preference
                    if brand_idx >= target_idx - 1:  # Allow one grade below
                        filtered_brands.append(brand)
                
                if filtered_brands:
                    material_copy = material.copy()
                    material_copy["brands"] = filtered_brands
                    filtered.append(material_copy)
            else:
                filtered.append(material)
    
    return filtered


def apply_regional_pricing(materials: List[Dict], region: str) -> List[Dict]:
    """
    Apply regional pricing multiplier to materials
    """
    multiplier = REGIONAL_MULTIPLIERS.get(region, 1.0)
    
    adjusted = []
    for material in materials:
        mat_copy = material.copy()
        mat_copy["rate_min"] = round(material["rate_min"] * multiplier, 2)
        mat_copy["rate_max"] = round(material["rate_max"] * multiplier, 2)
        
        if "brands" in material:
            adjusted_brands = []
            for brand in material["brands"]:
                brand_copy = brand.copy()
                brand_copy["rate"] = round(brand["rate"] * multiplier, 2)
                adjusted_brands.append(brand_copy)
            mat_copy["brands"] = adjusted_brands
        
        adjusted.append(mat_copy)
    
    return adjusted
